In [0]:
import numpy as np
from sklearn.datasets import load_boston
from sklearn.preprocessing import scale
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score



In [0]:
bunch = load_boston()
X = scale(bunch.data)
y = bunch.target

In [0]:
cv = KFold(n_splits=5, shuffle=True, random_state=42)
grid = np.linspace(1,10,200)



In [0]:
ans = []
for p in grid:
  neigh = KNeighborsRegressor(weights='distance',p=p)
  ans.append(cross_val_score(neigh, X, y=y, cv=cv, scoring='neg_mean_squared_error'))

In [43]:
ans

[array([-20.21899107, -12.49567191, -17.22129105, -11.83373336,
        -18.38354627]),
 array([-20.22607648, -12.57429075, -17.43647464, -12.07494178,
        -19.72740989]),
 array([-20.13329413, -12.65479751, -17.68764499, -11.92277511,
        -19.45497299]),
 array([-20.20518452, -12.96135285, -17.65835017, -11.91533174,
        -19.48836227]),
 array([-19.93196196, -12.90136373, -18.02078301, -11.95450061,
        -19.56667956]),
 array([-19.80364184, -12.87447015, -17.93740291, -12.11406897,
        -19.90257779]),
 array([-19.92462793, -13.24345009, -17.97716386, -12.09748856,
        -19.94081629]),
 array([-19.85066747, -13.80890388, -17.68416088, -12.66957076,
        -20.10781828]),
 array([-19.87699063, -13.94042247, -17.88657538, -12.68019921,
        -19.98685759]),
 array([-19.86064833, -13.98675631, -19.19762903, -12.65965632,
        -19.9198041 ]),
 array([-19.882023  , -13.69648154, -19.07122148, -12.97629251,
        -20.10014088]),
 array([-20.02953344, -13.777151

In [0]:
for i,arr in enumerate(ans):
  ans[i]=np.mean(arr)

In [48]:
ans

[-16.030646734221644,
 -16.40783870832999,
 -16.370696947059045,
 -16.445716308439433,
 -16.475057773399403,
 -16.526432329318258,
 -16.636709345898257,
 -16.82422425426731,
 -16.874209056598744,
 -17.124898819792115,
 -17.145231882153887,
 -17.01936008026763,
 -17.09913173771377,
 -16.801326640288362,
 -16.980745198189776,
 -17.03345890364771,
 -17.17164190266228,
 -17.181679169045047,
 -17.20826374287096,
 -17.32368019839837,
 -17.415118891722805,
 -17.385662319793234,
 -17.326038597662453,
 -17.336966976165666,
 -17.382648653849692,
 -17.656697514147996,
 -17.569894502250555,
 -17.319503281094065,
 -17.504732498340466,
 -17.5544941795893,
 -17.566035281733512,
 -17.596032653116758,
 -17.59909719750166,
 -17.282256557226717,
 -17.326364532505202,
 -17.485164572655087,
 -17.46023662680475,
 -17.47743618990552,
 -17.54616768641742,
 -17.528053717549938,
 -17.61469632990715,
 -17.608471489929777,
 -17.6500839868047,
 -17.889130893742156,
 -17.885633475989607,
 -18.10186246009226,
 -18.1