In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from scipy.sparse import csr_matrix as csr
import pandas as pd
import numpy as np

In [6]:
from sklearn import datasets

newsgroups = datasets.fetch_20newsgroups(
                    subset='all', 
                    categories=['alt.atheism', 'sci.space']
             )

In [79]:
vectorizer = TfidfVectorizer()
data = vectorizer.fit_transform(newsgroups.data,newsgroups.target)
target = newsgroups.target
feature_mapping = vectorizer.get_feature_names()
len(feature_mapping)
target

array([0, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
grid = {'C': np.power(10.0, np.arange(-5, 6))}
cv = KFold(n_splits=5, shuffle=True, random_state=241)
clf = SVC(kernel='linear', random_state=241)
gs = GridSearchCV(clf, grid, scoring='accuracy', cv=cv)
gs.fit(data,target)

GridSearchCV(cv=KFold(n_splits=5, random_state=241, shuffle=True),
             error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='linear',
                           max_iter=-1, probability=False, random_state=241,
                           shrinking=True, tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': array([1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02,
       1.e+03, 1.e+04, 1.e+05])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [78]:
gs.best_estimator_

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=241,
    shrinking=True, tol=0.001, verbose=False)

In [12]:
clf = SVC(C=1.0, kernel='linear', random_state=241)
cross_val_score(clf, data,y=target, scoring='accuracy', cv=cv)

array([0.99441341, 0.9859944 , 1.        , 0.99159664, 0.99439776])

In [17]:
clf.fit(data,y=target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=241,
    shrinking=True, tol=0.001, verbose=False)

In [30]:
coefs = clf.coef_

In [72]:
def max_n(row_data, row_indices, n):
    i = np.absolute(row_data).argsort()[-n:]
    # i = row_data.argpartition(-n)[-n:]
    top_values = row_data[i]
#     top_indices = row_indices[i]  # do the sparse indices matter?
    return top_values, i

ans = max_n(coefs.toarray().ravel(),0,10)

In [73]:
x = coefs.toarray().ravel()

In [74]:
ans[1]

array([22936, 15606,  5776, 21850, 23673, 17802,  5093,  5088, 12871,
       24019], dtype=int64)

In [75]:
np.take(feature_mapping,ans[1])

array(['sci', 'keith', 'bible', 'religion', 'sky', 'moon', 'atheists',
       'atheism', 'god', 'space'], dtype='<U80')

TypeError: bad operand type for abs(): 'list'

In [80]:
def x_square(x):
    return x**2

x_square2 = lambda x: x**2

In [81]:
x_square(4)

16

In [82]:
x_square2(4)

16