In [15]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer

In [7]:
df = pd.read_csv('abalone.csv')
df = df.replace(['M','I','F'],[1,0,-1])
df

Sex  Length  Diameter  Height  WholeWeight  ShuckedWeight  \
0       1   0.455     0.365   0.095       0.5140         0.2245   
1       1   0.350     0.265   0.090       0.2255         0.0995   
2      -1   0.530     0.420   0.135       0.6770         0.2565   
3       1   0.440     0.365   0.125       0.5160         0.2155   
4       0   0.330     0.255   0.080       0.2050         0.0895   
5       0   0.425     0.300   0.095       0.3515         0.1410   
6      -1   0.530     0.415   0.150       0.7775         0.2370   
7      -1   0.545     0.425   0.125       0.7680         0.2940   
8       1   0.475     0.370   0.125       0.5095         0.2165   
9      -1   0.550     0.440   0.150       0.8945         0.3145   
10     -1   0.525     0.380   0.140       0.6065         0.1940   
11      1   0.430     0.350   0.110       0.4060         0.1675   
12      1   0.490     0.380   0.135       0.5415         0.2175   
13     -1   0.535     0.405   0.145       0.6845         0.2725   
14     -1   0.470     0.355   0.100       0.4755         0.1675   
15      1   0.500     0.400   0.130       0.6645         0.2580   
16      0   0.355     0.280   0.085       0.2905         0.0950   
17     -1   0.440     0.340   0.100       0.4510         0.1880   
18      1   0.365     0.295   0.080       0.2555         0.0970   
19      1   0.450     0.320   0.100       0.3810         0.1705   
20      1   0.355     0.280   0.095       0.2455         0.0955   
21      0   0.380     0.275   0.100       0.2255         0.0800   
22     -1   0.565     0.440   0.155       0.9395         0.4275   
23     -1   0.550     0.415   0.135       0.7635         0.3180   
24     -1   0.615     0.480   0.165       1.1615         0.5130   
25     -1   0.560     0.440   0.140       0.9285         0.3825   
26     -1   0.580     0.450   0.185       0.9955         0.3945   
27      1   0.590     0.445   0.140       0.9310         0.3560   
28      1   0.605     0.475   0.180       0.9365         0.3940   
29      1   0.575     0.425   0.140       0.8635         0.3930   
...   ...     ...       ...     ...          ...            ...   
4147    1   0.695     0.550   0.195       1.6645         0.7270   
4148    1   0.770     0.605   0.175       2.0505         0.8005   
4149    0   0.280     0.215   0.070       0.1240         0.0630   
4150    0   0.330     0.230   0.080       0.1400         0.0565   
4151    0   0.350     0.250   0.075       0.1695         0.0835   
4152    0   0.370     0.280   0.090       0.2180         0.0995   
4153    0   0.430     0.315   0.115       0.3840         0.1885   
4154    0   0.435     0.330   0.095       0.3930         0.2190   
4155    0   0.440     0.350   0.110       0.3805         0.1575   
4156    1   0.475     0.370   0.110       0.4895         0.2185   
4157    1   0.475     0.360   0.140       0.5135         0.2410   
4158    0   0.480     0.355   0.110       0.4495         0.2010   
4159   -1   0.560     0.440   0.135       0.8025         0.3500   
4160   -1   0.585     0.475   0.165       1.0530         0.4580   
4161   -1   0.585     0.455   0.170       0.9945         0.4255   
4162    1   0.385     0.255   0.100       0.3175         0.1370   
4163    0   0.390     0.310   0.085       0.3440         0.1810   
4164    0   0.390     0.290   0.100       0.2845         0.1255   
4165    0   0.405     0.300   0.085       0.3035         0.1500   
4166    0   0.475     0.365   0.115       0.4990         0.2320   
4167    1   0.500     0.380   0.125       0.5770         0.2690   
4168   -1   0.515     0.400   0.125       0.6150         0.2865   
4169    1   0.520     0.385   0.165       0.7910         0.3750   
4170    1   0.550     0.430   0.130       0.8395         0.3155   
4171    1   0.560     0.430   0.155       0.8675         0.4000   
4172   -1   0.565     0.450   0.165       0.8870         0.3700   
4173    1   0.590     0.440   0.135       0.9660         0.4390   
4174    1   0.600     0.475   0.205       1.1760     

In [9]:
X = df.iloc[:,:-1]
y = df['Rings']

In [32]:
ans1 = []
kf = KFold(n_splits=5, random_state=1, shuffle=True)
for i in range(1,51):
    rfr = RandomForestRegressor(random_state=1,n_estimators=i)
    ans1.append(cross_val_score(rfr,X,y=y,scoring='r2',cv=kf))
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [31]:
ans

[array([ 0.19664192,  0.11762437,  0.25014945,  0.01794534, -0.03398699]),
 array([0.34998973, 0.31248787, 0.41442449, 0.29315165, 0.3364463 ]),
 array([0.43555625, 0.39450971, 0.4507151 , 0.34369426, 0.40769383]),
 array([0.4538912 , 0.43181681, 0.48833327, 0.40171715, 0.44811451]),
 array([0.46516582, 0.46183516, 0.50245236, 0.42456443, 0.4711443 ]),
 array([0.47016632, 0.46550248, 0.50380226, 0.44024387, 0.47726486]),
 array([0.47240359, 0.46311534, 0.51025053, 0.44945745, 0.48810233]),
 array([0.47827651, 0.47156308, 0.52085313, 0.45436419, 0.48961728]),
 array([0.48346912, 0.47368495, 0.52758124, 0.46537936, 0.49707042]),
 array([0.48225917, 0.48287088, 0.53756673, 0.46763961, 0.50670639]),
 array([0.48443577, 0.48035332, 0.53523372, 0.47505758, 0.49697519]),
 array([0.49359064, 0.48300729, 0.53465322, 0.4833414 , 0.50054834]),
 array([0.49857347, 0.4883515 , 0.53836004, 0.48430487, 0.5056994 ]),
 array([0.50562752, 0.49164162, 0.54044573, 0.48695012, 0.51191912]),
 array([0.50606

In [53]:
ans1 = [np.mean(i) for i in ans]

In [56]:
for i in ans1:
    if round(i,2) > 0.52:
        print(ans1.index(i),i)
        break

27 0.5256557724971402


In [50]:
len(ans1)

50

In [49]:
np.mean([0.51584313, 0.51265805, 0.55548875, 0.49695939, 0.52169615])

0.520529094